# Generated by Django 4.1.3 on 2022-12-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
        migrations.AlterField(
            model_name="user",
            name="image_file",
            field=models.ImageField(
                blank=True,
                default="default_media/avatar.jpg",
                null=True,
                upload_to="uploaded_media",
            ),
        ),
    ]
