# Generated by Django 4.1.3 on 2022-11-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_comment_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_file",
            field=models.ImageField(
                blank=True,
                default="default_media/Portraits_2.png",
                null=True,
                upload_to="uploaded_media",
            ),
        ),
    ]
