# Generated by Django 4.1.3 on 2022-11-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="self_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
