# Generated by Django 4.1.3 on 2022-11-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="en_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="manga",
            name="ru_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
