# Generated by Django 4.1.3 on 2022-11-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0002_genre_self_id_alter_genre_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="title",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
