# Generated by Django 4.1.3 on 2022-11-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0002_alter_manga_en_name_alter_manga_ru_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manga",
            name="translator",
        ),
        migrations.DeleteModel(
            name="Translator",
        ),
    ]
