# Generated by Django 4.1.3 on 2022-12-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0003_remove_manga_translator_delete_translator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
