# Generated by Django 4.1.3 on 2022-12-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0004_alter_genre_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="en_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="manga",
            name="ru_name",
            field=models.CharField(max_length=200),
        ),
    ]
