# Generated by Django 4.1.3 on 2022-12-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0005_alter_manga_en_name_alter_manga_ru_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="self_id",
        ),
    ]
