# Generated by Django 4.1.3 on 2022-12-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0007_manga_dir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
